spring.application.name=tienda

# puerto por donde escucha nuestro servidor web
server.port=80

# para definir el formato de salida del log en cuanto a horas y minutos
logging.pattern.dateformat=hh:mm

# evitamos la salida del banner de spring
spring.main.banner-mode=off

# definimos el cache como falso en desarrollo, en producción será true
spring.thymeleaf.cache=false
